export { default as homePageQuery } from './homePage'
export { default as aboutPageQuery } from './aboutPage'
export { default as inspoPageQuery } from './inspoPage'
export { default as loginPageQuery } from './loginPage'
export { default as painterPageQuery } from './painterPage'
export { default as registerPageQuery } from './registerPage'
export { default as shopPageQuery } from './shopPage'
export { default as colorPageQuery } from './colorsPage'
