export const homeId = 'cG9zdDozMQ=='
export const registerId = 'cG9zdDoxMTM='
export const loginId = 'cG9zdDoxMTA='
export const aboutId = 'cG9zdDoxMzI='
export const painterdId = 'cG9zdDoxNTc='
export const shopId = 'cG9zdDoyMDI='
export const inspoId = 'cG9zdDoyMDY='
export const colorsId = 'cG9zdDo1MDk='
