export const MENU_SHOW: string = 'MENU_SHOW'
export const FOOTER_SHOW: string = 'FOOTER_SHOW'
export const MODAL_CLOSE: string = 'MODAL_CLOSE'
export const SHOW_LOADER: string = 'SHOW_LOADER'
export const SHOW_TOAST: string = 'SHOW_TOAST'
