export const MENU_SHOW: string = 'MENU_SHOW'
export const FOOTER_SHOW: string = 'FOOTER_SHOW'
export const SHOW_MODAL: string = 'SHOW_MODAL'
export const SHOW_LOADER: string = 'SHOW_LOADER'
export const SHOW_TOAST: string = 'SHOW_TOAST'
export const SET_SHOW_FILTERS: string = 'SET_SHOW_FILTERS'
