export const SET_ITEM: string = 'SET_ITEM'
export const ADDED_ITEM: string = 'ADDED_ITEM'
export const UPDATE_QUANTITY: string = 'UPDATE_QUANTITY'
export const REMOVE_ITEM: string = 'REMOVE_ITEM'
export const UPDATE_SHIPPING: string = 'UPDATE_SHIPPING'
